// import the grid class
import { Grid } from "./gridClass.js";
// import the facility class
import { Facility } from "./facilityClass.js";
// import residence classes
import {
    Residence,
    LuxuryResidence,
    ComfortableResidence,
    AffordableResidence,
} from "./residenceClass.js";
// import essential services classes
import {
    EmergencyServices,
    EducationCenter,
    MedicalCenter,
    GovernmentFacility,
    PowerPlant,
} from "./essentialsClass.js";
// import industrial classes
import {
    IndustrialFacility,
    Factory,
    EnvironmentalFacility,
    Warehouse,
} from "./industrialClass.js";
// import commercial classes
import { Commercials, Store, Restaurant, Office } from "./commercialsClass.js";
// import planetary defense class
import { PlanetaryDefense } from "./planetaryDefense.js";

/**
 * Represents a Planet in the simulation.
 * Manages the grid of facilities, game state, and financial aspects.
 */
export class Planet {
    private _grid: Grid;
    private _buildingsBuilt: number = 0;
    private _maxBuildings: number;
    private _userMoney: number = 5000000000;
    private _currentTime: number = 0;
    private _totalPopulation: number = 0;
    private _totalPollution: number = 0;
    private _hasPlanetaryDefense: boolean = false;
    private _isGameOver: boolean = false;
    private _totalPowerGenerated: number = 0;
    private _totalPowerUsed: number = 0;
    private _monthlyBalance: number = 0;

    /**
     * Creates an instance of Planet.
     * @param rows The number of rows in the planet's grid.
     * @param col The number of columns in the planet's grid.
     */
    constructor(rows: number, col: number) {
        this._grid = new Grid(rows, col);
        this._maxBuildings = this._grid.rows * this._grid.columns;
    }

    // Getters
    /**
     * Gets the grid of the planet.
     * @returns The Grid object.
     */
    public get grid(): Grid {
        return this._grid;
    }

    /**
     * Gets the number of buildings built on the planet.
     * @returns The number of buildings.
     */
    public get buildingsBuilt(): number {
        return this._buildingsBuilt;
    }

    /**
     * Gets the maximum number of buildings allowed on the planet.
     * @returns The maximum number of buildings.
     */
    public get maxBuildings(): number {
        return this._maxBuildings;
    }

    /**
     * Gets the user's current money.
     * @returns The amount of user money.
     */
    public get userMoney(): number {
        return this._userMoney;
    }

    /**
     * Gets the current simulation time (in months).
     * @returns The current time.
     */
    public get currentTime(): number {
        return this._currentTime;
    }

    /**
     * Gets the total population on the planet.
     * @returns The total population.
     */
    public get totalPopulation(): number {
        return this._totalPopulation;
    }

    /**
     * Gets the total pollution on the planet.
     * @returns The total pollution.
     */
    public get totalPollution(): number {
        return this._totalPollution;
    }

    /**
     * Checks if the planet has a Planetary Defense facility.
     * @returns True if a Planetary Defense exists, false otherwise.
     */
    public get hasPlanetaryDefense(): boolean {
        return this._hasPlanetaryDefense;
    }

    /**
     * Checks if the game is over.
     * @returns True if the game is over, false otherwise.
     */
    public get isGameOver(): boolean {
        return this._isGameOver;
    }

    /**
     * Gets the total power generated by power plants.
     * @returns The total power generated.
     */
    public get totalPowerGenerated(): number {
        return this._totalPowerGenerated;
    }

    /**
     * Gets the total power consumed by facilities.
     * @returns The total power used.
     */
    public get totalPowerUsed(): number {
        return this._totalPowerUsed;
    }

    /**
     * Gets the current power balance (generated - used).
     * @returns The power balance.
     */
    public get powerBalance(): number {
        return this._totalPowerGenerated - this._totalPowerUsed;
    }

    /**
     * Gets the current monthly balance.
     * @returns The monthly balance.
     */
    public get monthlyBalance(): number {
        return this._monthlyBalance;
    }

    /**
     * Calculates and applies all monthly updates to the planet's state.
     */
    public calculateMonthlyUpdates(): void {
        this._currentTime++;
        this.updatePlanetaryDefenseStatus();

        if (!this._hasPlanetaryDefense) {
            this.checkForDisasters();
            if (this._isGameOver) return;
        }

        this.updatePowerStats();
        this.resetMonthlyCounters();

        const allFacilities = this.getAllFacilities();
        this.processFacilities(allFacilities);
        this.applyEnvironmentalReductions(allFacilities);
        this.finalizeMonthlyUpdates();
    }

    /**
     * Updates the status of whether the planet has a Planetary Defense.
     * @private
     */
    private updatePlanetaryDefenseStatus(): void {
        this._hasPlanetaryDefense =
            this._grid.countFacilities("PlanetaryDefense") > 0;
    }

    /**
     * Resets monthly counters for population, pollution, and balance.
     * @private
     */
    private resetMonthlyCounters(): void {
        this._totalPopulation = 0;
        this._totalPollution = 0;
        this._monthlyBalance = 0;
    }

    /**
     * Processes each facility to update pollution, revenue, maintenance, and population.
     * @param facilities An array of Facility objects to process.
     * @private
     */
    private processFacilities(facilities: Facility[]): void {
        facilities.forEach((facility) => {
            if (!(facility instanceof EnvironmentalFacility)) {
                this._totalPollution += facility.calcMonthlyPollution();
            }
        });

        facilities.forEach((facility) => {
            facility.incrementMonths();
            const revenue = this.calculateFacilityRevenue(facility);
            const maintenance = this.calculateFacilityMaintenance(facility);
            this._monthlyBalance += revenue - maintenance;

            if (facility instanceof Residence) {
                this.processResidence(facility);
            }
        });
    }

    /**
     * Calculates the monthly revenue for a given facility.
     * @param facility The Facility object to calculate revenue for.
     * @returns The calculated monthly revenue.
     * @private
     */
    private calculateFacilityRevenue(facility: Facility): number {
        if (!facility.hasPower) return 0;

        if (facility instanceof Commercials) {
            return facility.calcMonthlyRevenue(this._grid);
        }
        if (facility instanceof Factory) {
            return this.calculateFactoryRevenue(facility);
        }
        return facility.calcMonthlyRevenue();
    }

    /**
     * Calculates the monthly revenue specifically for a Factory, considering nearby Warehouses.
     * @param factory The Factory object to calculate revenue for.
     * @returns The calculated monthly factory revenue.
     * @private
     */
    private calculateFactoryRevenue(factory: Factory): number {
        if (!factory.hasPower) return 0;

        let revenue = factory.calcMonthlyRevenue();

        const hasWarehouseNearby = this._grid.hasFacilityTypeInRadius(
            factory.x,
            factory.y,
            5,
            "Warehouse"
        );

        return hasWarehouseNearby ? revenue * 2 : revenue;
    }

    /**
     * Calculates the monthly maintenance cost for a given facility.
     * @param facility The Facility object to calculate maintenance for.
     * @returns The calculated monthly maintenance cost.
     * @private
     */
    private calculateFacilityMaintenance(facility: Facility): number {
        return facility instanceof Commercials
            ? facility.calcMaintenanceCost(this._grid)
            : facility.calcMaintenanceCost();
    }

    /**
     * Processes a Residence facility to update its population.
     * @param residence The Residence object to process.
     * @private
     */
    private processResidence(residence: Residence): void {
        residence.updatePopulation(this._grid);
        this._totalPopulation += residence.currPopulation;
    }

    /**
     * Applies pollution reductions based on Environmental Facilities.
     * @param facilities An array of all Facility objects.
     * @private
     */
    private applyEnvironmentalReductions(facilities: Facility[]): void {
        const originalPollution = this._totalPollution;
        let totalReduction = 0;

        facilities.forEach((facility) => {
            if (facility instanceof EnvironmentalFacility) {
                const affected = this._grid
                    .getFacilityInRadius(
                        facility.x,
                        facility.y,
                        facility.pollutionReductionRadius
                    )
                    .filter((f) => !(f instanceof EnvironmentalFacility));

                const localPollution = affected.reduce((sum, f) => {
                    const dx = f.x - facility.x;
                    const dy = f.y - facility.y;
                    const distance = Math.sqrt(dx * dx + dy * dy);

                    if (distance <= facility.pollutionReductionRadius) {
                        return sum + f.calcMonthlyPollution();
                    }
                    return sum;
                }, 0);

                const facilityReduction = Math.min(
                    localPollution,
                    facility.maxPollutionReduction
                );
                totalReduction += facilityReduction;

                console.log(
                    `EnvFac at ${facility.x},${facility.y} reduced ${facilityReduction} pollution`
                );
            }
        });

        const effectiveReduction = Math.min(totalReduction, originalPollution);
        this._totalPollution = Math.max(
            0,
            originalPollution - effectiveReduction
        );

        console.log(
            `Pollution: ${originalPollution} -> ${this._totalPollution} (reduced by ${effectiveReduction})`
        );
    }

    /**
     * Finalizes monthly updates, including money balance and game over check.
     * @private
     */
    private finalizeMonthlyUpdates(): void {
        this._userMoney += this._monthlyBalance;
        this._monthlyBalance = 0;

        if (this._userMoney < 0) {
            this._isGameOver = true;
            alert(`Game Over! Final Score: ${this.calculateScore()}`);
        }
    }

    /**
     * Updates power generation and consumption stats for all facilities.
     * Prioritizes power distribution to essential facilities.
     * @private
     */
    private updatePowerStats(): void {
        const allFacilities = this.getAllFacilities();

        this._totalPowerGenerated = allFacilities.reduce(
            (sum, f) => sum + (f instanceof PowerPlant ? f.powerOutput : 0),
            0
        );

        const consumers = allFacilities
            .filter((facility) => !(facility instanceof PowerPlant))
            .sort(
                (a, b) => this.getPowerPriority(a) - this.getPowerPriority(b)
            );

        let powerLeft = this._totalPowerGenerated;
        consumers.forEach((facility) => {
            const canPower = powerLeft >= facility.powerConsumption;
            facility.updatePowerStatus(canPower);
            if (canPower) powerLeft -= facility.powerConsumption;
        });

        allFacilities.forEach((facility) => {
            if (facility instanceof PowerPlant) {
                facility.updatePowerStatus(true);
            }
        });

        this._totalPowerUsed = this._totalPowerGenerated - powerLeft;
    }

    /**
     * Gets the power priority for a given facility type. Lower numbers mean higher priority.
     * @param facility The Facility object to get the priority for.
     * @returns The power priority level.
     * @private
     */
    private getPowerPriority(facility: Facility): number {
        if (facility instanceof Residence) return 1;
        if (
            facility.typeOf.includes("Center") ||
            facility.typeOf === "EmergencyServices" ||
            facility.typeOf === "GovernmentFacility"
        )
            return 2;
        if (facility.typeOf === "Store" || facility.typeOf === "Restaurant")
            return 3;
        if (facility instanceof IndustrialFacility) return 4;
        return 5;
    }

    /**
     * Retrieves the facility at the specified grid coordinates.
     * @param rows The row index of the facility.
     * @param col The column index of the facility.
     * @returns The Facility object at the given coordinates, or null if no facility exists.
     */
    public getFacilityAt(rows: number, col: number): Facility | null {
        const facility = this._grid.getFacility(rows, col);
        if (facility === null) {
            return null;
        }
        return facility;
    }

    /**
     * Retrieves all facilities of a specific type.
     * @param type The type of facility to retrieve (e.g., "Residence", "Factory").
     * @returns An array of Facility objects matching the specified type.
     */
    public getFacilitiesOfType(type: string): Facility[] {
        const facilities: Facility[] = [];
        for (let i = 0; i < this._grid.rows; i++) {
            for (let j = 0; j < this._grid.columns; j++) {
                const facility = this._grid.getFacility(i, j);
                if (facility?.typeOf.includes(type)) {
                    facilities.push(facility);
                }
            }
        }
        return facilities;
    }

    /**
     * Retrieves all facilities currently built on the planet.
     * @returns An array of all Facility objects.
     */
    public getAllFacilities(): Facility[] {
        const facilities: Facility[] = [];
        for (let i = 0; i < this._grid.rows; i++) {
            for (let j = 0; j < this._grid.columns; j++) {
                const facility = this._grid.getFacility(i, j);
                if (facility) {
                    facilities.push(facility);
                }
            }
        }
        return facilities;
    }

    /**
     * Calculates the player's final score based on happy and content population and pollution.
     * @returns The calculated score.
     */
    public calculateScore(): number {
        let happyPop = 0;
        let contentPop = 0;

        this.getAllFacilities()
            .filter((facility) => facility.typeOf.includes("Residence"))
            .forEach((residence) => {
                const res = residence as Residence;
                happyPop += res.happyPopulation;
                contentPop += res.contentPopulation;
            });

        return 3 * happyPop + contentPop - this._totalPollution;
    }

    /**
     * Checks for random disasters (asteroid or alien attacks) that can end the game.
     * Only occurs if no Planetary Defense is present.
     * @private
     */
    private checkForDisasters(): void {
        if (Math.random() < 0.01) {
            // asteroid
            this._isGameOver = true;
            alert("Game over. Your final score: " + this.calculateScore());
        }
        if (Math.random() < 0.01) {
            // alien
            this._isGameOver = true;
            alert("Game over. Your final score: " + this.calculateScore());
        }
    }

    /**
     * Decreases the count of buildings built.
     * @param value The amount to decrease the building count by.
     */
    public decreaseBuildingCount(value: number): void {
        this._buildingsBuilt = Math.max(0, this._buildingsBuilt - value);
    }

    // Building methods

    /**
     * Checks if the user can afford a given cost.
     * @param cost The cost to check against user money.
     * @returns True if the user can afford it, false otherwise.
     */
    public canAfford(cost: number): boolean {
        return this._userMoney >= cost;
    }

    /**
     * Attempts to build a Store at the specified coordinates.
     * @param x The x-coordinate for the Store.
     * @param y The y-coordinate for the Store.
     * @returns True if the Store was successfully built, false otherwise.
     */
    public buildStore(x: number, y: number): boolean {
        return this.buildFacility(new Store(x, y), 2000000);
    }

    /**
     * Attempts to build a Restaurant at the specified coordinates.
     * @param x The x-coordinate for the Restaurant.
     * @param y The y-coordinate for the Restaurant.
     * @returns True if the Restaurant was successfully built, false otherwise.
     */
    public buildRestaurant(x: number, y: number): boolean {
        return this.buildFacility(new Restaurant(x, y), 250000);
    }

    /**
     * Attempts to build an Office at the specified coordinates.
     * @param x The x-coordinate for the Office.
     * @param y The y-coordinate for the Office.
     * @returns True if the Office was successfully built, false otherwise.
     */
    public buildOffice(x: number, y: number): boolean {
        return this.buildFacility(new Office(x, y), 3000000);
    }

    /**
     * Attempts to build a Warehouse at the specified coordinates.
     * @param x The x-coordinate for the Warehouse.
     * @param y The y-coordinate for the Warehouse.
     * @returns True if the Warehouse was successfully built, false otherwise.
     */
    public buildWarehouse(x: number, y: number): boolean {
        return this.buildFacility(new Warehouse(x, y), 10000000);
    }

    /**
     * Attempts to build an Environmental Facility at the specified coordinates.
     * @param x The x-coordinate for the Environmental Facility.
     * @param y The y-coordinate for the Environmental Facility.
     * @returns True if the Environmental Facility was successfully built, false otherwise.
     */
    public buildEnvFacility(x: number, y: number): boolean {
        return this.buildFacility(new EnvironmentalFacility(x, y), 200000000);
    }

    /**
     * Attempts to build a Factory at the specified coordinates.
     * @param x The x-coordinate for the Factory.
     * @param y The y-coordinate for the Factory.
     * @returns True if the Factory was successfully built, false otherwise.
     */
    public buildFactory(x: number, y: number): boolean {
        return this.buildFacility(new Factory(x, y), 50000000);
    }

    /**
     * Attempts to build a Power Plant at the specified coordinates.
     * @param x The x-coordinate for the Power Plant.
     * @param y The y-coordinate for the Power Plant.
     * @returns True if the Power Plant was successfully built, false otherwise.
     */
    public buildPP(x: number, y: number): boolean {
        return this.buildFacility(new PowerPlant(x, y), 500000000);
    }

    /**
     * Attempts to build an Education Center at the specified coordinates.
     * @param x The x-coordinate for the Education Center.
     * @param y The y-coordinate for the Education Center.
     * @returns True if the Education Center was successfully built, false otherwise.
     */
    public buildEduCenter(x: number, y: number): boolean {
        return this.buildFacility(new EducationCenter(x, y), 500000000);
    }

    /**
     * Attempts to build a Medical Center at the specified coordinates.
     * @param x The x-coordinate for the Medical Center.
     * @param y The y-coordinate for the Medical Center.
     * @returns True if the Medical Center was successfully built, false otherwise.
     */
    public buildMedCenter(x: number, y: number): boolean {
        return this.buildFacility(new MedicalCenter(x, y), 1000000000);
    }

    /**
     * Attempts to build Emergency Services at the specified coordinates.
     * @param x The x-coordinate for Emergency Services.
     * @param y The y-coordinate for Emergency Services.
     * @returns True if Emergency Services was successfully built, false otherwise.
     */
    public buildEmergencyServ(x: number, y: number): boolean {
        return this.buildFacility(new EmergencyServices(x, y), 100000000);
    }

    /**
     * Attempts to build a Government Facility at the specified coordinates.
     * @param x The x-coordinate for the Government Facility.
     * @param y The y-coordinate for the Government Facility.
     * @returns True if the Government Facility was successfully built, false otherwise.
     */
    public buildGovernment(x: number, y: number): boolean {
        return this.buildFacility(new GovernmentFacility(x, y), 100000000);
    }

    /**
     * Attempts to build a Luxury Residence at the specified coordinates.
     * @param x The x-coordinate for the Luxury Residence.
     * @param y The y-coordinate for the Luxury Residence.
     * @returns True if the Luxury Residence was successfully built, false otherwise.
     */
    public buildLuxury(x: number, y: number): boolean {
        return this.buildFacility(new LuxuryResidence(x, y), 1000000000);
    }

    /**
     * Attempts to build a Comfortable Residence at the specified coordinates.
     * @param x The x-coordinate for the Comfortable Residence.
     * @param y The y-coordinate for the Comfortable Residence.
     * @returns True if the Comfortable Residence was successfully built, false otherwise.
     */
    public buildComfort(x: number, y: number): boolean {
        return this.buildFacility(new ComfortableResidence(x, y), 500000000);
    }

    /**
     * Attempts to build an Affordable Residence at the specified coordinates.
     * @param x The x-coordinate for the Affordable Residence.
     * @param y The y-coordinate for the Affordable Residence.
     * @returns True if the Affordable Residence was successfully built, false otherwise.
     */
    public buildAffordable(x: number, y: number): boolean {
        return this.buildFacility(new AffordableResidence(x, y), 50000000);
    }

    /**
     * Attempts to build a Planetary Defense facility at the specified coordinates.
     * Can only be built if one doesn't already exist.
     * @param x The x-coordinate for the Planetary Defense.
     * @param y The y-coordinate for the Planetary Defense.
     * @returns True if the Planetary Defense was successfully built, false otherwise.
     */
    public buildPlanetaryDefense(x: number, y: number): boolean {
        if (this._hasPlanetaryDefense) {
            return false;
        }
        this._hasPlanetaryDefense = true;
        return this.buildFacility(new PlanetaryDefense(x, y), 1000000000000);
    }

    /**
     * Private helper method to handle the general logic for building any facility.
     * @param facility The Facility object to build.
     * @param cost The cost of building the facility.
     * @returns True if the facility was successfully built, false otherwise.
     * @private
     */
    private buildFacility(facility: Facility, cost: number): boolean {
        if (!this.canAfford(cost)) {
            return false;
        }
        if (this._grid.getFacility(facility.x, facility.y) !== null) {
            return false;
        }
        if (facility instanceof Residence) {
            if (!facility.canBeBuilt(this._grid)) {
                console.log(
                    "Failed residential requirements at",
                    facility.x,
                    facility.y
                );
                console.log(
                    "Nearby facilities:",
                    this._grid.getFacilityInRadius(facility.x, facility.y, 5)
                );
                return false;
            }
        }
        if (facility instanceof IndustrialFacility) {
            if (!facility.canBeBuilt(this._grid)) {
                console.log("Missing Industrial Requirments");
                return false;
            }
        }
        this._userMoney -= cost;
        this._buildingsBuilt++;
        return this._grid.addFacility(facility, facility.x, facility.y);
    }
}