// import the facility class
import { Facility } from "./facilityClass.js";
// import the grid class
import { Grid } from "./gridClass.js";

/**
 * An abstract base class for all residential facilities.
 * Extends the base Facility class and provides common properties and methods for residences.
 */
export abstract class Residence extends Facility {
    protected _happyPopulation: number = 0;
    protected _contentPopulation: number = 0;
    protected _currPopulation: number = 0;
    protected _currMaxPopulation: number = 0;
    protected _monthsSinceBuilt: number = 0;

    /**
     * Constructs a Residence facility.
     * @param x The x-coordinate on the grid.
     * @param y The y-coordinate on the grid.
     * @param buildCost The cost to build the residence.
     * @param powerConsumption The power consumed by the residence.
     * @param typeOf The type of residence (e.g., "LuxuryResidence", "ComfortableResidence").
     */
    constructor(
        x: number,
        y: number,
        buildCost: number,
        powerConsumption: number,
        typeOf: string
    ) {
        super(x, y, buildCost, powerConsumption, typeOf);
    }

    // Getters
    /**
     * Gets the number of happy residents in the facility.
     * @returns The happy population count.
     */
    public get happyPopulation(): number {
        return this._happyPopulation;
    }

    /**
     * Gets the number of content residents in the facility.
     * @returns The content population count.
     */
    public get contentPopulation(): number {
        return this._contentPopulation;
    }

    /**
     * Gets the current population of the facility.
     * @returns The current population.
     */
    public get currPopulation(): number {
        return this._currPopulation;
    }

    /**
     * Gets the current maximum population capacity of the facility.
     * @returns The current maximum population.
     */
    public get currMaxPopulation(): number {
        return this._currMaxPopulation;
    }

    /**
     * Gets the number of months since the facility was built.
     * @returns The months since built.
     */
    public get monthsSinceBuilt(): number {
        return this._monthsSinceBuilt;
    }

    /**
     * Checks if the residence has all required essential services within range.
     * Required services include EducationCenter, MedicalCenter, EmergencyServices, GovernmentFacility, and PowerPlant.
     * @param grid The game grid to check for facilities.
     * @returns True if all essential services are present, false otherwise.
     */
    public hasRequiredServices(grid: Grid): boolean {
        const essentialServices = [
            "EducationCenter",
            "MedicalCenter",
            "EmergencyServices",
            "GovernmentFacility",
            "PowerPlant",
        ];
        return essentialServices.every((service) =>
            grid.hasFacilityTypeInRadius(this.x, this.y, 8, service)
        );
    }

    /**
     * Checks if the residence has required amenities (Store and Restaurant) within range.
     * @param grid The game grid to check for facilities.
     * @returns True if all required amenities are present, false otherwise.
     */
    public hasRequiredAmenities(grid: Grid): boolean {
        return (
            grid.hasFacilityTypeInRadius(this.x, this.y, 5, "Store") &&
            grid.hasFacilityTypeInRadius(this.x, this.y, 3, "Restaurant")
        );
    }

    /**
     * Determines if the residence can be built at its current location based on service and amenity requirements.
     * @param grid The game grid to check requirements against.
     * @returns True if the residence can be built, false otherwise.
     */
    public canBeBuilt(grid: Grid): boolean {
        return (
            this.hasRequiredServices(grid) && this.hasRequiredAmenities(grid)
        );
    }

    /**
     * Abstract method to calculate the monthly revenue generated by the residence.
     * @returns The monthly revenue.
     */
    public abstract calcMonthlyRevenue(): number;

    /**
     * Abstract method to calculate the monthly pollution generated by the residence.
     * @returns The monthly pollution.
     */
    public abstract calcMonthlyPollution(): number;

    /**
     * Abstract method to update the population of the residence based on game conditions.
     * @param grid The game grid, used to check for nearby services or amenities.
     */
    public abstract updatePopulation(grid: Grid): void;

    /**
     * Increases the current population of the residence towards its maximum capacity.
     * Growth is typically a percentage of the maximum population.
     * @protected
     */
    protected growPopulation(): void {
        if (this._currPopulation < this._currMaxPopulation) {
            const growthAmount = Math.floor(this._currMaxPopulation * 0.1);
            this._currPopulation = Math.min(
                this._currPopulation + growthAmount,
                this._currMaxPopulation
            );
        }
    }

    /**
     * Updates the breakdown of happy and content population based on a given happy ratio.
     * @param happyRatio The ratio (0-1) of the current population that is happy.
     * @protected
     */
    protected updatePopulationCategories(happyRatio: number): void {
        this._happyPopulation = Math.floor(this._currPopulation * happyRatio);
        this._contentPopulation = this._currPopulation - this._happyPopulation;
    }
}

/**
 * Represents a Luxury Residence facility.
 * Provides high revenue but has strict requirements for population growth.
 */
export class LuxuryResidence extends Residence {
    private readonly _absoluteMaxPopulation: number = 10000;
    private _hasStore: boolean = false;
    private _hasRestaurant: boolean = false;

    /**
     * Constructs a Luxury Residence.
     * @param x The x-coordinate on the grid.
     * @param y The y-coordinate on the grid.
     */
    constructor(x: number, y: number) {
        super(x, y, 1000000000, 100, "LuxuryResidence");
        this._currMaxPopulation = 0;
    }

    /**
     * Calculates the monthly revenue for the Luxury Residence.
     * Revenue scales with the number of residents in thousands.
     * @returns The calculated monthly revenue.
     */
    public calcMonthlyRevenue(): number {
        if (!this.hasPower) return 0;
        const thousandsOfResidents = Math.floor(this.currPopulation / 1000);
        return thousandsOfResidents * 15000000;
    }

    /**
     * Calculates the monthly maintenance cost for the Luxury Residence.
     * Cost includes a base amount and an additional cost per thousand residents.
     * @returns The calculated monthly maintenance cost.
     */
    public calcMaintenanceCost(): number {
        const baseCost = 10000000;
        const perThousandCost =
            Math.floor(this.currPopulation / 1000) * 1000000;
        return baseCost + perThousandCost;
    }

    /**
     * Calculates the monthly pollution generated by the Luxury Residence.
     * Pollution scales with the number of residents in thousands.
     * @returns The calculated monthly pollution.
     */
    public calcMonthlyPollution(): number {
        return Math.floor(this.currPopulation / 1000) * 500;
    }

    /**
     * Updates the population of the Luxury Residence based on amenity availability and essential services.
     * Population growth is affected by the presence of a Store and Restaurant.
     * @param grid The game grid to check for amenities and services.
     */
    public updatePopulation(grid: Grid): void {
        this._hasStore = grid.hasFacilityTypeInRadius(
            this.x,
            this.y,
            5,
            "Store"
        );
        this._hasRestaurant = grid.hasFacilityTypeInRadius(
            this.x,
            this.y,
            3,
            "Restaurant"
        );

        if (this._hasStore && this._hasRestaurant) {
            this._currMaxPopulation = this._absoluteMaxPopulation;
        } else {
            this._currMaxPopulation = 5000;
        }

        if (
            super.hasRequiredServices(grid) &&
            this._currPopulation < this._currMaxPopulation
        ) {
            const monthlyGrowth = Math.floor(this._currMaxPopulation * 0.1);
            this._currPopulation = Math.min(
                this._currPopulation + monthlyGrowth,
                this._currMaxPopulation
            );

            this._happyPopulation = Math.floor(this._currPopulation * 0.5);
            this._contentPopulation =
                this._currPopulation - this._happyPopulation;
        }

        this.incrementMonths;
    }

    /**
     * Checks if both luxury amenities (Store and Restaurant) are present.
     * @returns True if both are present, false otherwise.
     */
    public get luxuryAmenitiesStatus(): boolean {
        return this._hasStore && this._hasRestaurant;
    }

    /**
     * Provides a descriptive string of the status of luxury amenities.
     * @returns A string indicating whether a Store and Restaurant are present.
     */
    public get luxuryAmenitiesStatusDescription(): string {
        return `Store: ${this._hasStore ? "✅" : "❌"}, Restaurant: ${
            this._hasRestaurant ? "✅" : "❌"
        }`;
    }
}

/**
 * Represents a Comfortable Residence facility.
 * Offers moderate revenue and population capacity.
 */
export class ComfortableResidence extends Residence {
    private readonly _absoluteMaxPopulation: number = 15000;
    private _hasStore: boolean = false;
    private _hasRestaurant: boolean = false;

    /**
     * Constructs a Comfortable Residence.
     * @param x The x-coordinate on the grid.
     * @param y The y-coordinate on the grid.
     */
    constructor(x: number, y: number) {
        super(x, y, 500000000, 50, "ComfortableResidence");
        this._currMaxPopulation = 0;
    }

    /**
     * Calculates the monthly revenue for the Comfortable Residence.
     * Revenue scales with the number of residents in thousands.
     * @returns The calculated monthly revenue.
     */
    public calcMonthlyRevenue(): number {
        if (!this.hasPower) return 0;
        const thousandsOfResidents = Math.floor(this.currPopulation / 1000);
        return thousandsOfResidents * 1000000;
    }

    /**
     * Calculates the monthly maintenance cost for the Comfortable Residence.
     * Cost includes a base amount and an additional cost per thousand residents.
     * @returns The calculated monthly maintenance cost.
     */
    public calcMaintenanceCost(): number {
        const baseCost = 40000;
        const perThousandCost = Math.floor(this.currPopulation / 1000) * 50000;
        return baseCost + perThousandCost;
    }

    /**
     * Calculates the monthly pollution generated by the Comfortable Residence.
     * Pollution scales with the number of residents in thousands.
     * @returns The calculated monthly pollution.
     */
    public calcMonthlyPollution(): number {
        return Math.floor(this.currPopulation / 1000) * 50;
    }

    /**
     * Updates the population of the Comfortable Residence based on amenity availability and essential services.
     * @param grid The game grid to check for amenities and services.
     */
    public updatePopulation(grid: Grid): void {
        this._hasStore = grid.hasFacilityTypeInRadius(
            this.x,
            this.y,
            5,
            "Store"
        );
        this._hasRestaurant = grid.hasFacilityTypeInRadius(
            this.x,
            this.y,
            3,
            "Restaurant"
        );

        this._currMaxPopulation = this._absoluteMaxPopulation;

        if (
            super.hasRequiredServices(grid) &&
            this._currPopulation < this._currMaxPopulation
        ) {
            const monthlyGrowth = Math.floor(this._currMaxPopulation * 0.1);
            this._currPopulation = Math.min(
                this._currPopulation + monthlyGrowth,
                this._currMaxPopulation
            );

            this._happyPopulation = Math.floor(this._currPopulation * 0.25);
            this._contentPopulation =
                this._currPopulation - this._happyPopulation;
        }

        this.incrementMonths();
    }

    /**
     * Checks if both comfortable amenities (Store and Restaurant) are present.
     * @returns True if both are present, false otherwise.
     */
    public get comfortableAmenitiesStatus(): boolean {
        return this._hasStore && this._hasRestaurant;
    }

    /**
     * Provides a descriptive string of the status of comfortable amenities.
     * @returns A string indicating whether a Store and Restaurant are present.
     */
    public get comfortableAmenitiesStatusDescription(): string {
        return `Store: ${this._hasStore ? "✅" : "❌"}, Restaurant: ${
            this._hasRestaurant ? "✅" : "❌"
        }`;
    }
}

/**
 * Represents an Affordable Residence facility.
 * Provides basic housing with higher population capacity but lower revenue.
 */
export class AffordableResidence extends Residence {
    private readonly _absoluteMaxPopulation: number = 25000;
    private _hasStore: boolean = false;
    private _hasRestaurant: boolean = false;

    /**
     * Constructs an Affordable Residence.
     * @param x The x-coordinate on the grid.
     * @param y The y-coordinate on the grid.
     */
    constructor(x: number, y: number) {
        super(x, y, 50000000, 25, "AffordableResidence");
        this._currMaxPopulation = 0;
    }

    /**
     * Calculates the monthly revenue for the Affordable Residence.
     * Revenue scales with the number of residents in thousands.
     * @returns The calculated monthly revenue.
     */
    public calcMonthlyRevenue(): number {
        if (!this.hasPower) return 0;
        const thousandsOfResidents = Math.floor(this.currPopulation / 1000);
        return thousandsOfResidents * 10000;
    }

    /**
     * Calculates the monthly maintenance cost for the Affordable Residence.
     * Cost includes a base amount and an additional cost per thousand residents.
     * @returns The calculated monthly maintenance cost.
     */
    public calcMaintenanceCost(): number {
        const baseCost = 8000;
        const perThousandCost = Math.floor(this.currPopulation / 1000) * 2000;
        return baseCost + perThousandCost;
    }

    /**
     * Calculates the monthly pollution generated by the Affordable Residence.
     * Pollution scales with the number of residents in thousands.
     * @returns The calculated monthly pollution.
     */
    public calcMonthlyPollution(): number {
        return Math.floor(this.currPopulation / 1000) * 10;
    }

    /**
     * Updates the population of the Affordable Residence based on amenity availability and essential services.
     * @param grid The game grid to check for amenities and services.
     */
    public updatePopulation(grid: Grid): void {
        this._hasStore = grid.hasFacilityTypeInRadius(
            this.x,
            this.y,
            5,
            "Store"
        );
        this._hasRestaurant = grid.hasFacilityTypeInRadius(
            this.x,
            this.y,
            3,
            "Restaurant"
        );

        this._currMaxPopulation = this._absoluteMaxPopulation;

        if (
            super.hasRequiredServices(grid) &&
            this._currPopulation < this._currMaxPopulation
        ) {
            const monthlyGrowth = Math.floor(this._currMaxPopulation * 0.1);
            this._currPopulation = Math.min(
                this._currPopulation + monthlyGrowth,
                this._currMaxPopulation
            );

            this._happyPopulation = Math.floor(this._currPopulation * 0.1);
            this._contentPopulation =
                this._currPopulation - this._happyPopulation;
        }

        this.incrementMonths();
    }

    /**
     * Checks if both affordable amenities (Store and Restaurant) are present.
     * @returns True if both are present, false otherwise.
     */
    public get affordableAmenitiesStatus(): boolean {
        return this._hasStore && this._hasRestaurant;
    }

    /**
     * Provides a descriptive string of the status of affordable amenities.
     * @returns A string indicating whether a Store and Restaurant are present.
     */
    public get affordableAmenitiesStatusDescription(): string {
        return `Store: ${this._hasStore ? "✅" : "❌"}, Restaurant: ${
            this._hasRestaurant ? "✅" : "❌"
        }`;
    }
}